### ISSUE TITLE
Paths containing snake_case parameters aren't converted into camelCase

### ISSUE THREAD

**Issue by rcstatic** [cellular/oazapfts#11]
To reproduce, change a path in the petstore.json demo, say, from `"/pet/{petId}"` to `"/pet/{pet_id}"` and the corresponding `parameters` entry from `"petId"` to `"pet_id"`. The generated client will have an incorrect string template literal:

```ts
export async function getPetById(petId: number, opts?: RequestOpts) {
    return await _.fetchJson(`/pet/${pet_id}`, {
        ...opts
    }) as Pet;
}
```

(The interpolated variable is still in snake_case).

I believe the fix would be as simple as changing this bit in `createUrlExpression`:

https://github.com/cellular/oazapfts/blob/eecf678c2b64e5261a0498ed395923ca7edd82a2/src/generate.ts#L111-L112

to:

```ts
    (__, head, expression, literal) => {
      spans.push({ expression: ts.createIdentifier(_.camelCase(expression)), literal });
```

Happy to submit a pull request if needed.

**Comment by fgnass** [comment]
Fixed in 2.2.3
