### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by rtfpessoa** [cellular/oazapfts#14]
I stumbled on the oazapfts (https://github.com/cellular/oazapfts) library recently, while I was in the beginning of my own generator.
I found that the ideas are very aligned with mine and the code is very approachable.

There are some features I would like to have, like multiples files output, separate model generation from the actual endpoint call, wrappers for endpoint responses, payload validation, ...

I would like to know if you have any interest in receiving contributions? and If you have any other kind of plans and missing features list for the library?

**Comment by fgnass** [comment]
We (at least for now) consider the library to be feature complete but are open for ideas and PRs. I would like to learn about the rationale behind the features you mentioned:

* _multiples files output_: What would go into the different files? How would you like to see things being split (and why)?
* _separate model generation_: You mean actual classes? Would they contain any logic or would they be plain data transfer objects? 
* _wrappers for endpoint responses_: What would these wrappers do? 
* _payload validation_: Request or response validation (or both)?

**Comment by rtfpessoa** [comment]
Thanks for the quick answer.
We (at least for now) consider the library to be feature complete but are open for ideas and PRs. I would like to learn about the rationale behind the features you mentioned:

> multiples files output: What would go into the different files? How would you like to see things being split (and why)?
The idea would be to have the models separate from the actual endpoints implementation and then, since some apis can grow a lot, we could have one file per tag in the swagger.

> separate model generation: You mean actual classes? Would they contain any logic or would they be plain data transfer objects?
Just play interfaces/types but separate from the implementation. You could even just generate the models and not the implementation in some cases.

> Wrappers for endpoint responses: What would these wrappers do?
In some cases where we do not have a schema defined inside components for a response it ends up being an inline struct. If you created something like a named type for each response it could even be referenced in the rest of the code.
e.g.:
```typescript
type myOperationIdResponse = myOperationIdResponse200 | myOperationIdResponse404
type myOperationIdResponse200 = {
  foo: string
}
type myOperationIdResponse404 = Error
type Error = {
  message: string
}
```

> payload validation: Request or response validation (or both)?
I was just considering response. Specifically two parts. We could always validate if the status codes returned were in the spec (or if a default is defined) and if it is a json media we could validate the schema and reject the promise if it does not match.
Ideally I would always resolve promises that are specified in the spec and the response would be a union type.

Let me know what you think of each of them.

**Comment by fgnass** [comment]
> > multiples files output: What would go into the different files? How would you like to see things being split (and why)?

> The idea would be to have the models separate from the actual endpoints implementation and then, since some apis can grow a lot, we could have one file per tag in the swagger.

Can you elaborate on the reasoning behind it? Are you concerned about the file size or is it just about code organization?  
How would you handle models that are shared across endpoints/tags?

> > separate model generation: You mean actual classes? Would they contain any logic or would they be plain data transfer objects?

> Just play interfaces/types but separate from the implementation. You could even just generate the models and not the implementation in some cases.

This sounds as if you have a certain use case in mind. Can you explain in which situation this would be useful?

> > Wrappers for endpoint responses: What would these wrappers do?

> In some cases where we do not have a schema defined inside components for a response it ends up being an inline struct. If you created something like a named type for each response it could even be referenced in the rest of the code.

Ah okay, _synthetic type aliases for responses_ so to say. We usually refer to these unnamed types as `ReturnType<typeof myOperation>` in our code which I find quite intuitive, but I can see how an alias could be useful if the return type was a union type. You mention that you would prefer if all promises resolved to a union type. I think this raises an interesting question: Currently only the first response with a code < 400 is considered. The fact that there could be multiple such responses is ignored. And since rejections can't be explicitly typed we are left with untyped errors. While I see the shortcomings of this approach I still like it for its simplicity from a API-consumer's perspective: I can simply await the call and don't have to add an if/else block afterwards. I guess it highly depends on the particular API which flavor is preferable. So maybe this should become a command line option?

> > payload validation: Request or response validation (or both)?

> I was just considering response. Specifically two parts. We could always validate if the status codes returned were in the spec (or if a default is defined) and if it is a json media we could validate the schema and reject the promise if it does not match.
Ideally I would always resolve promises that are specified in the spec and the response would be a union type.

I like the idea of validating the status code. JSON schema validation should be an opt-in feature as it would add a lot of overhead that you don't want in case you trust your server.

**Comment by rtfpessoa** [comment]
> > > multiples files output: What would go into the different files? How would you like to see things being split (and why)?
> 
> > The idea would be to have the models separate from the actual endpoints implementation and then, since some apis can grow a lot, we could have one file per tag in the swagger.
> 
> Can you elaborate on the reasoning behind it? Are you concerned about the file size or is it just about code organization?

The concern is mostly for being able to navigate in the files. Since they can really grow a lot.

> How would you handle models that are shared across endpoints/tags?

That is a good question, I have a couple of ideas:
* One solution could be to have all the models in the same file (just separate from the endpoints)
* Another could be to separate by tag and duplicate if they are used in multiple endpoints
* Another could be to separate by a model tag passed by an extra `x-` parameter, or just one file by default

> > > separate model generation: You mean actual classes? Would they contain any logic or would they be plain data transfer objects?
> 
> > Just play interfaces/types but separate from the implementation. You could even just generate the models and not the implementation in some cases.
> 
> This sounds as if you have a certain use case in mind. Can you explain in which situation this would be useful?

One common use case is to share data models for other things that are not apis. It is a bit of a over use for swagger but since components are a main entity you can take profit from the heavy lifting of generation to get just models for events systems for example. And you get this in a similar way as you get your apis.

> > > Wrappers for endpoint responses: What would these wrappers do?
> 
> > In some cases where we do not have a schema defined inside components for a response it ends up being an inline struct. If you created something like a named type for each response it could even be referenced in the rest of the code.
> 
> Ah okay, _synthetic type aliases for responses_ so to say. We usually refer to these unnamed types as `ReturnType<typeof myOperation>` in our code which I find quite intuitive, but I can see how an alias could be useful if the return type was a union type. You mention that you would prefer if all promises resolved to a union type. I think this raises an interesting question: Currently only the first response with a code < 400 is considered. The fact that there could be multiple such responses is ignored. And since rejections can't be explicitly typed we are left with untyped errors. While I see the shortcomings of this approach I still like it for its simplicity from a API-consumer's perspective: I can simply await the call and don't have to add an if/else block afterwards. I guess it highly depends on the particular API which flavor is preferable. So maybe this should become a command line option?

That sounds completely fair. I guess it could even be an [extension](https://swagger.io/docs/specification/openapi-extensions/) per endpoint, since in certain cases the errors might be important to deal and get a nice type while others you might want to deal with them in a generic way.

> > > payload validation: Request or response validation (or both)?
> 
> > I was just considering response. Specifically two parts. We could always validate if the status codes returned were in the spec (or if a default is defined) and if it is a json media we could validate the schema and reject the promise if it does not match.
> > Ideally I would always resolve promises that are specified in the spec and the response would be a union type.
> 
> I like the idea of validating the status code. JSON schema validation should be an opt-in feature as it would add a lot of overhead that you don't want in case you trust your server.

Also agree with it, since it would probably require one runtime dependency for the validation.


I already have a playground where I tested some of this. Based on your feedback I will work a bit on it and bring some PRs so you can provide more precise feedback.

**Comment by fgnass** [comment]
Closing this to move the conversation to separate issues.
