### ISSUE TITLE
Use with Axios?

### ISSUE THREAD

**Issue by gaggle** [cellular/oazapfts#211]
Hi, I planned to use this library but have the underlying requests be handled via Axios. But this library seems quite tied to nodeFetch? I tried various approaches to get axios into the fetch slot, but calls like `res.headers.get` makes assumptions on the return shape, etc.

Is there a vision for a more generic interface-based callback way of handling requests and responses to open up for other http approaches? I think I was expecting some callbacks I could hook into, where I'd adapt the input to axios & adapt axios' response back to oazapfts' requirements.

**Comment by wvffle** [comment]
I also look forward to axios support

**Comment by jonkoops** [comment]
There is no intention of making this library dependent on Axios, however in the future it might be possible to make the fetching logic separate from the logic that builds the request details (such as URL, headers, etc).

**Comment by sfedorov-at-wiley** [comment]
Can confirm that in our prject we would like to provide axios instance to be used by generated code

**Comment by jonkoops** [comment]
Closing this issue as there are currently no plans to use anything but the standardized Fetch API. Note that under the hood Axios also uses the Fetch API.

There is no reason to use any other HTTP library in my opinion as this library is supposed to abstract the HTTP client away as much as possible.

**Comment by Xiphe** [comment]
Fully agree with @jonkoops on this one. Would like to know what benefits you'd hope to gain by using axios, maybe we can help to find a good solution

**Comment by sfedorov-at-wiley** [comment]
@Xiphe In our case it is a decision from architecture council. Right now we have zero benefits from using axios instead of fetch, but it is proposed, that in future we will need feature-rich functionality like interceptors. 

So problem is not with code, but more of an ideological obstacle. We need some kind of proof that we either can use axios with library, achieve similar functionality, or axios is not needed for generated code at all.

**Comment by Xiphe** [comment]
@sfedorov-at-wiley thanks for elaborating 👍 

While you'll not be able to just plug in an instance of axios, you'll still be able to replace `fetch` with a custom implementation (See [Overriding the defaults](https://github.com/cellular/oazapfts#overriding-the-defaults)).

Technically this enables you to create a custom adapter from fetch API to axios. Or add interceptors there.

```ts
import * as api from "./api.ts";

api.defaults.fetch = (input: RequestInfo | URL, init?: RequestInit | undefined) => {
  /* ... translate to axios or add interceptors */
};
```

**Comment by sfedorov-at-wiley** [comment]
@Xiphe Thank you!
I'll quote your reply to our tech lead
