### ISSUE TITLE
Release/Publish a new version

### ISSUE THREAD

**Issue by Asvarox** [cellular/oazapfts#229]
Hi,

Is it possible to have a new release? The master branch contains https://github.com/cellular/oazapfts/pull/169 -- a bugfix needed to make RTKQuery CodeGen work properly with enums https://github.com/reduxjs/redux-toolkit/issues/1788 and it would be great to be able to update this package there.

**Comment by Lantianyou** [comment]
Hi, guys having the same issue here, would be really nice to publish this.

**Comment by jonkoops** [comment]
Version 3.6.0 has now been [released](https://github.com/cellular/oazapfts/releases/tag/v3.6.0). Apologies for the delay, I have not had much time to work on this project.
