### ISSUE TITLE
When will JSON response in HttpError feature be released?

### ISSUE THREAD

**Issue by dalane** [cellular/oazapfts#26]
I'm anticipating the release to NPM that includes the JSON response in the HttpError. Any forecast for when this is planned?

**Comment by fgnass** [comment]
You can `npm install oazapfts@next` to get the latest RC from the the `next` branch.

**Comment by dalane** [comment]
Great, I'll use that for the moment.

Thanks.

**Comment by ealtunyay** [comment]
Thanks for this, but those later versions seem to include a breaking change of how errors are handled (does not throw, #20)
