### ISSUE TITLE
Stepping in as co-maintainer

### ISSUE THREAD

**Issue by Xiphe** [cellular/oazapfts#266]
Hey @jonkoops @fgnass

Just wanted to let you guys know that i'll be trying to invest some time into this project, try to solve some issues respond to some PRs etc.

Do you @jonkoops still work at celluar/FFW? And is any of you admin of this project?

**Comment by fgnass** [comment]
Hi @Xiphe, I set your repo access to _maintainer_. Thanks for helping out!

**Comment by jonkoops** [comment]
I'm just an open-source maintainer working at Red Hat, we currently don't use oazapfts but we might in the future. I jumped on as I was integrating it in one of my previous projects, hence I am a bit on and off.

**Comment by jonkoops** [comment]
Closing this as @Xiphe is now a maintainer.

**Comment by Xiphe** [comment]
Cool Thanks everybody let me know when I can help with anything 👍
