### ISSUE TITLE
Explode parameter serialisation

### ISSUE THREAD

**Issue by Xiphe** [cellular/oazapfts#269]
1. According to [spec](https://swagger.io/docs/specification/serialization/#query) query parameters should be serialised as exploded form by default `https://example.org/users?id=1&id=2&id=3` instead of `https://example.org/users?id=1,2,3` (we're doing that currently).

2. There are some possible combinations like `pipeDelimited` + `explode` that are currently handled not according to spec

Technically changing these should be considered a breaking change since some servers might expect the current behaviour.
On the other hand me and my colleague just spend a noticeable chunk of time debugging an issue that rooted in this.

@jonkoops do you have opinions on wether this should be addressed and if it would be a breaking change.

**Comment by Xiphe** [comment]
@fgnass do you have opinions about this? (And is it ok when I ping you for your opinion about oazapfts things or do you focus on other things now?)

**Comment by fgnass** [comment]
@Xiphe I'm all for following the specs as close as possible. And yes, this should be a breaking change.
