### ISSUE TITLE
Type "any" from tsoa generates nested Record

### ISSUE THREAD

**Issue by ra100** [cellular/oazapfts#28]
I'm using `tsoa` to generate openapi spec. In Types I have something like this:

```ts
interface VersionData {
  [key: string]: any;
}

class Version {
   public data: VersionData;
}
```

which generates this in openapispec:
```yaml
         Version:
            properties:
                data:
                    $ref: '#/components/schemas/VersionData'
            required:
                - data
            type: object
            additionalProperties: false
// ...
          VersionData:
            description: 'Record Version Data'
            properties: {}
            type: object
            additionalProperties:
                additionalProperties: true
            example:
                html: '<p>Some content</p>'
```

And when I generate client from this, I get this type for version:

```ts
export type VersionData = {
    [key: string]: {
        [key: string]: any;
    };
};
```

which is kinda wrong, as this would require me to use:

```ts
createVersion({data: {someKey: {someNested: 'string'}}})
// instead of:
createVersion({data: {someKey: 'string'}})
```

Am I doing something wrong here?

**Comment by fgnass** [comment]
Hm, the following part looks suspicious:

```yml
type: object
  additionalProperties:
    additionalProperties: true
```

Any idea, why tsoa generates it this way?

**Comment by fgnass** [comment]
Could you post a stripped down (but working) version of your spec?

**Comment by ra100** [comment]
Yes, that part looks weird, and it is probably the issue. And I don't know why it's generating in that way. Maybe I should try defining it as a `type VersionData = Record<string, any>`, but that was not generating openapi right. I might try that again.
 
```yaml
components:
  examples: {}
  headers: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas:
    VersionData:
      description: 'Record Version Data'
      properties: {}
      type: object
      additionalProperties:
        additionalProperties: true
      example:
        html: '<p>Some content</p>'
    NewRecordBody:
      properties:
        data:
          $ref: '#/components/schemas/VersionData'
      required:
        - data
      type: object
      additionalProperties: false
  securitySchemes: {}
info:
  title: 'title'
  version: 1.0.0
  description: 'description'
openapi: 3.0.0
paths:
  /records:
    post:
      operationId: createRecord
      responses:
        '201':
          content:
            application/json:
              schema:
                type: object
          description: 'Record with Version data Created'
      security: []
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRecordBody'
servers:
  - url: 'http://localhost:3003/v1'
    description: local
```

**Comment by fgnass** [comment]
I'm not entirely sure, but I'd say that oazapfts does the right thing in this case and this is a bug in tsoa.

**Comment by ra100** [comment]
Thanks, I'll try some more things and maybe report bug there.

**Comment by WoH** [comment]
> I'm not entirely sure, but I'd say that oazapfts does the right thing in this case and this is a bug in tsoa.

Hi, maintainer of tsoa here, so I'd like to explain: 

```js
{
  type: object,
  additionalProperties: {
    additionalProperties: true
  }
}
```

I think we'd agree that this Part is fine:
```js
{
  type: object,
  additionalProperties: {
    // any schema here
  }
}
```

We currently implement TS types `any`/`unknown` as 
```js
{ 
  additionalProperties: true,
}
```

Which explains the output. While I've been made aware that most code generators have an issue with 
```js
{ 
  additionalProperties: true,
}
```
but usually translate an empty schema
```js
{ }
```
to `any`, I'd like to point out that `additionalProperties: true` is the default value, so both of these JSON Schemas are afaik equivalent.

**Comment by fgnass** [comment]
Thanks @WoH for chiming in, that reasoning makes sense. I'll see what I can do on our side to support this.

**Comment by WoH** [comment]
This is causing issues with some other codegen aswell, so I'll try to make sure we produce
```js
{ }
```
in the future. If 
```js
{
  type: object,
  additionalProperties: {
  }
}
```
will produce the result, you don't need to do anything in order to be compatible with out output.

I still wanted to share this in order to give context. Not sure if it helps, but I hope it does :smile:
