### ISSUE TITLE
feat: support "const" keyword

### ISSUE THREAD

**Issue by jayalfredprufrock** [cellular/oazapfts#291]
Would you accept a PR for adding support for the "const" keyword? It's basically syntactic sugar for a single value enum, however its becoming more popular in the wild since it's been a part of the JSON schema spec since draft-06 and is now a part of OAS 3.1. 

I know the current implementation brings in types from OAS 3.0 so is this out of the question until the library makes a decision to support 3.1?

**Comment by Xiphe** [comment]
Hey @jayalfredprufrock 

from what I understand there is no decision against 3.1. It's just that nobody has jet decided to start working on 3.1 support. 

And if you would like to be that person, assuming OAS 3.1 is backward-compatible with 3.0 (Meaning when oazapfts supports 3.1, it still works with backend serving 3.0) you have my back!

Do you have an overview of what needs to change to fully support 3.1?
Would be great to have that as a kind of milestone-issue and then implement step by step.

The one situation I would want to avoid is users seeing partial support for 3.1 and then assume we support everything. So I'd probably go with a `oas-3.1` branch and preview releases until we're fully compatible.

---

Honestly, you just made me aware on 3.1, I was under the assumption that [3.0.3](https://swagger.io/specification/) is the latest 🙈

Glancing over https://spec.openapis.org/oas/v3.1.0 I cant find details for a "cont" keyword, could you help me find it or provide an example.

**Comment by jayalfredprufrock** [comment]
Thanks for the quick response! So the thing about OAS 3.1 is they finally reached full parity with the JSON schema spec, specifically the 2020-12 draft. (See https://github.com/OAI/OpenAPI-Specification/releases) They link to the general spec in that release, but you have to dig a little deeper to get to the "validation" portion of the draft, where you'll find the mention of the "const" keyword: https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-6.1.3  Since it's unclear to me which portions of the JSON schema were not previously implemented, I couldn't say exactly what all the differences are between the 3.0 and 3.1 spec. I would think the differences can't be too extreme or they would have spent a little more time detailing things in the release notes and/or had a major version bump, but I can't be sure.

But in terms of backwards compatibility, there is one thing that I noticed. They apparently dropped support for the "nullable" keyword (one of the few features _not_ ever included in the JSON spec), encouraging the use of the "null" type instead, which can be used in an array of types to indicate nullability. For that reason, "officially" supporting 3.1 while maintaining support for 3.0 would either need to mean:

1. supporting a union of their features
2. using the specific OAS version in the schema to selectively apply behavior

The first option is clearly easier to implement, however if the intention is to strictly adopt the spec, the second option might be preferred. I'd also argue that if the first option is acceptable, slowly supporting _new_ features of OAS 3.1 that don't come with backwards compatibility issues would be acceptable as well. You wouldn't advertise full OAS 3.1 support, just that certain features are available and that "official" 3.1 support would come later as a major version upgrade once all the dust has settled.

Oddly enough, my interest in all of this is largely because a library I'm integrating with right now, [TypeBox](https://github.com/sinclairzx81/typebox), currently uses "anyOf" in combination with "const" to represent literal unions (as opposed to supporting enum strings). Oasapftz comes close to interpreting things correctly, but ends up produce a union like `string | string` instead of treating the const value as a literal. I would be satisfied if either library supported my use case, however I know the maintainer of TypeBox is trying hard to not support multiple forms of union representations and instead has chosen to go all in on "anyOf" since its more flexible and capable of representing all other union constructs.

Regardless of where any of this lands, I really appreciate the time invested in Oasapftz. It's a fantastic library that really hits a sweet spot in terms of ease of use and features. Thanks!

**Comment by Xiphe** [comment]
I understand, thanks for elaborating!

Let's go with just adding const-support for now in order to deblock the incompatability with TypeBox 👍 Will await your PR, let me know when I can help.

As for the rest I'd like to hear if @jonkoops has an opinion about OAS 3.1?
