### ISSUE TITLE
Types are generated with spaces in the names when spec has titles with spaces

### ISSUE THREAD

**Issue by rtfpessoa** [cellular/oazapfts#40]
This can be replicated by running the CLI over 
https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml

which will generate types like:

```ts
export type A Pet = {
    id?: number;
    category?: Pet category;
    name: string;
    photoUrls: string[];
    tags?: Pet Tag[];
    status?: "available" | "pending" | "sold";
};
export type An uploaded response = {
    code?: number;
    "type"?: string;
    message?: string;
};
```

**Comment by gjsduarte** [comment]
The issue seems to be coming from https://github.com/cellular/oazapfts/blob/4fb5720685626140b7f9982ea1e364faa6a27575/src/codegen/generate.ts#L231

**Comment by rtfpessoa** [comment]
@fgnass do you have any suggestions on how to fix this?

**Comment by kahirokunn** [comment]
Dot and hyphen symbols have a similar problem. 😢

**Comment by pollen8** [comment]
thanks for fixing that - any chance we can get a release with these change?

**Comment by tevariou** [comment]
> thanks for fixing that - any chance we can get a release with these change?

I concur. @fgnass a new release would be great!

**Comment by fgnass** [comment]
@pollen8 If I'm not mistaken this was fixed by 25d67ba6519be8ad41661a15a412d5167b847c82 which was included in oazapfts@3.2.0. Please let me know if I am missing something and this is a different issue.

**Comment by pollen8** [comment]
I'm not sure if this conforms to the swagger spec but now I have a proto file 

```
    /**
     * This is some comment in the proto
     */
    privacy_level?: PrivacyLevel;
}
```

which resolves to a swagger definition:

```
 "privacy_level": {
          "$ref": "#/definitions/PrivacyLevel",
          "title": "This is some comment in the proto"
        }
```
        And generates types:

 ```
        privacy_level?: ThisIsSomCommentInTheProto
 ```
        
With long descriptions this becomes pretty unwieldy

**Comment by pollen8** [comment]
just to confirm that I re-tested this with 3.3.1 and can no longer replicate
