### ISSUE TITLE
Possibility of plugins or maybe even a collaboration?

### ISSUE THREAD

**Issue by phryneas** [cellular/oazapfts#41]
Hey there :wave: (Moin!)

I'm Lenz, a co-maintainer of [reduxjs/redux toolkit](https://github.com/reduxjs/redux-toolkit). 
Right now, we're in the process of building a redux-based data-fetching client over at [rtk-incubator/rtk-query](https://github.com/rtk-incubator/rtk-query) (name subject to change), similar to the likes of msw or react-query, but with a central api definition and as a consequence of that, much stronger TypeScript support and extra bonuses like automatic invalidation of certain queries on calling mutations.

I would like to ship rtk-query from the early days with some kind of code generator for OpenAPI specs. 
And I've looked through a lot of them and most of them are template-based, which would work for basic use cases, but there are also scenarios that could *really*  benefit from adding more info from the schema that could hardly be added using just a template approach. 
So, I've found `oazapfts` and I really like the approach. But at the current point, I'd need to fork & heavily modify it. So, before doing that, I just wanted to ask: have you considered a small plugin system for the actual code generation? 
Or are you even in on the idea of collaborating?

As for what I want to generate, you can take a look at the docs, but here is [one example](https://rtk-query-docs.netlify.app/concepts/mutations/#commented-posts-service):
```ts
import { createApi, fetchBaseQuery } from '@rtk-incubator/rtk-query';

export interface Post {
  id: number;
  name: string;
}

type PostsResponse = Post[];

export const postApi = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: '/' }),
  entityTypes: ['Posts'],
  endpoints: (build) => ({
    getPosts: build.query<PostsResponse, void>({
      query: () => 'posts',
      provides: (result) => [...result.map(({ id }) => ({ type: 'Posts', id })), { type: 'Posts', id: 'LIST' }],
    }),
    getPost: build.query<Post, number>({
      query: (id) => `posts/${id}`,
      provides: (_, id) => [{ type: 'Posts', id }],
    }),
    updatePost: build.mutation<Post, Partial<Post>>({
      query(data) {
        const { id, ...body } = data;
        return {
          url: `posts/${id}`,
          method: 'PUT',
          body,
        };
      },
      invalidates: (_, { id }) => [{ type: 'Posts', id }],
    }),
  }),
});
```

Most of that could simply be generated with any template-based generator.
Except for these parts:
`      provides: (result) => [...result.map(({ id }) => ({ type: 'Posts', id })), { type: 'Posts', id: 'LIST' }],`
`      provides: (_, id) => [{ type: 'Posts', id }],`
and
`      invalidates: (_, { id }) => [{ type: 'Posts', id }],`
as these need information on the structure of the returned data.

Right now, my idea would be to generate such a `createApi`call with as much info as could safely be extracted from the swagger file and allow the users to override some things (like that `{ type: 'Posts', id: 'LIST' }` part for example) manually.

So, yeah, big proposal from a strange guy on the internet :)
If any of these peaks your interested, maybe we could do a video call one of these days?

Greetings from Würzburg, 
Lenz

**Comment by fgnass** [comment]
Moin Lenz, thanks for reaching out! I would love to see redux toolkit using oazapfts, so let's see what we can do. 

I'm generally not a big fan of plugin systems as they are super hard to get right from a design point of view. Maybe we can think of a way where oazapfts exports all the building blocks you'd need in rtk-query to generate the code you want? So instead of passing a plugin to oazapfts you pick the modules/functions you need from it to assemble your own library. I'd be totally open to any kind refactoring heading into that direction. This would be somehow similar to what https://github.com/cotype/build-client does, although in your case you'd probably want to swap out the whole AST generation instead of just modifying it afterwards.

That being said I also wonder whether the thing you want to achieve could be done entirely on the type level? You'd create a standard oazapfts client and pass it to rtk-query which in turn would wrap it and apply some type magic to return the proper typings? This is the approach we take in our internal `useApi` react hooks.

**Comment by phryneas** [comment]
Just having building blocks would be totally fine. 
I was even thinking about doing all that myself, buy you have already done so much (and I guess, learned so much on the way!) that it would be pretty stupid to start all over again :)

The result would be kinda 50:50 real runtime code and types - as I'd ideally want to generate most of that hunk of code above from a swagger specification. 
So it's not only the types, which I could probably just extract from a readily-created client, but also to generate code (especially looking at `provides`, which would not be possible with current template systems) that is based on the swagger spec.

So, it would probably generate something like
```ts
// all types as used in `schemas` go here

function generatedApi({url, variables} /* types for possible values of this generated from the server */) {
  const baseUrl = // calculate baseUrl from url & variables

  return createApi({
    baseQuery: fetchBaseQuery({ baseUrl' }),
    entityTypes: ['Posts'], /* derived "type names" from `schemas` */,
     endpoints: (build) => ({
      /* query-type endpoints generated from GET operations */
      getPosts: build.query<ReturnType, ParametersType>({
        query: (parameters) => 'posts', // returns path with route & query parameters replaced in
        provides: (result) => [...result.map(({ id }) => ({ type: 'Posts', id }))], // generated from the structure of ReturnType
      }),
      /* mutation-type endpoints generated from all other REST operations */
      getPosts: build.query<ReturnType, ParametersType>({
        query: (parameters) => ({
          url 'posts', // returns path with route & query parameters replaced in
          method: 'METHOD',
          body: // content of type application/json
        }),
        invalidates: ... // we should probably not generate this as it might be too risky
      }),
  })
}
```

All that with the grain of salt: I haven't actively used swagger much myself (early graphql adopter here ^^) and I never really had to parse it up to now by myself, so  I might have gotten some details wrong up there ^^

**Comment by phryneas** [comment]
So, I'm kinda :eyes: on the helpers you have in `tscodegen.ts` there and would probably just copy out some of the general logic in `generate.ts` from what I#ve seen from skimming the source so far.

**Comment by fgnass** [comment]
I could imagine that there are some useful utilities inside `generate.ts` like [getTypeFromSchema](https://github.com/cellular/oazapfts/blob/master/src/codegen/generate.ts#L317) which are currently not accessible on their own as they are buried inside a huge closure. One option to make them available would be to refactor the whole file into a class.

**Comment by phryneas** [comment]
Yup, exactly something like that would be a dream!

**Comment by msutkowski** [comment]
Just wanted to chime in here, I've been wanting to do this same type of thing for [msw](https://github.com/mswjs/msw) -- it'd be awesome to be able to generate a list of mock handlers from an open API schema :)

**Comment by fgnass** [comment]
@msutkowski maybe meanwhile https://www.npmjs.com/package/open-api-mocker can help? We use it in our oazapfts test suite and it's awesome!

**Comment by phryneas** [comment]
@fgnass hehe, Matt is a contributor on `msw` and just wants to extend their features ;)

It's also pretty neat, as it is just a service worker. We use it in the tests of rtk-query and even in our codesandboxes to just "provide apis" without anyone ever having to start a server.

**Comment by fgnass** [comment]
I should have clicked that link! 😅

**Comment by phryneas** [comment]
Just that you don't do double work: I've created https://github.com/phryneas/oazapfts/tree/expose-class
So far I'm not 100% sure if I have exposed everything I need, so I haven't filed a PR yet.

I have:
* converted the `generateApi` method to a class
* added lots of exports
* converted everything over to TS 4.1.2 and the new `ts.factory` (with some small any casts where stuff is now readonly, not 100% sure if that's legit)
